import { test, expect } from "./test";
import { config } from "dotenv";
import { readdir, readFile, unlink } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { getDb } from "../../apps/web/src/lib/db";
config({ path: "apps/web/.env.local", quiet: true });
const emails: string[] = [];
const organization = `Facturation ${randomUUID().slice(0, 8)}`;
const password = "Une phrase de passe navigateur 123!";

async function latestCode(email: string) {
  const dir = process.env.LOCAL_MAIL_DIR!;
  const files = await readdir(dir);
  const mails = await Promise.all(files.filter(file => file.endsWith(".json")).map(async file => JSON.parse(await readFile(path.join(dir, file), "utf8"))));
  const mail = mails.filter(item => item.to === email).sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0];
  return /\b\d{6}\b/.exec(mail.text)![0];
}

test.afterAll(async () => {
  const db = getDb();
  const memberships = await db.membership.findMany({ where: { user: { email: { in: emails } } } });
  const organizationIds = memberships.map(item => item.organizationId);
  await db.document.deleteMany({ where: { organizationId: { in: organizationIds }, sourceDocumentId: { not: null } } });
  await db.document.deleteMany({ where: { organizationId: { in: organizationIds } } });
  await db.customer.deleteMany({ where: { organizationId: { in: organizationIds } } });
  await db.user.deleteMany({ where: { email: { in: emails } } });
  await db.organization.deleteMany({ where: { id: { in: organizationIds } } });
  await db.authChallenge.deleteMany({ where: { email: { in: emails } } });
  const dir = process.env.LOCAL_MAIL_DIR!;
  for (const file of await readdir(dir).catch(() => [])) {
    if (file.endsWith(".json") && emails.includes(JSON.parse(await readFile(path.join(dir, file), "utf8")).to)) await unlink(path.join(dir, file));
  }
  await db.$disconnect();
});

test("devis B2C, identité historique, devise, échéance et devis B2B", async ({ page }) => {
  const ownerEmail = `browser-billv2-${randomUUID()}@example.test`;
  emails.push(ownerEmail);
  await page.goto("/inscription");
  await page.getByRole("radio", { name: /^Entreprise/ }).check();
  await page.getByLabel("Votre nom").fill("Camille Billing");
  await page.getByLabel("Nom de votre entreprise").fill(organization);
  await page.getByLabel("Adresse email").fill(ownerEmail);
  await page.getByLabel("Mot de passe", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Créer mon espace" }).click();
  await expect(page).toHaveURL(/verification/);
  await page.getByLabel("Code de vérification").fill(await latestCode(ownerEmail));
  await page.getByRole("button", { name: "Valider et accéder" }).click();
  await expect(page).toHaveURL(/espace/);
  await page.getByRole("link", { name: "Organisation" }).click();
  await page.getByLabel("Devise").fill("USD");
  await page.getByLabel("Délai de règlement (jours)").fill("15");
  await page.getByRole("button", { name: "Enregistrer l’identité" }).click();
  await expect(page.getByText("L’identité de l’émetteur a été enregistrée.")).toBeVisible();
  await page.getByRole("link", { name: "Clients", exact: true }).click();
  await page.getByLabel("Identité").selectOption("PERSON");
  await page.getByLabel("Prénom").fill("Marie");
  await page.getByLabel("Nom", { exact: true }).fill("Dupont");
  await page.getByRole("button", { name: "Créer la fiche" }).click();
  await expect(page.getByRole("heading", { name: "Marie Dupont" })).toBeVisible();
  await page.getByRole("link", { name: "Devis", exact: true }).click();
  await page.getByLabel("Titre").fill("Cours B2C");
  await page.getByLabel("Destinataire").selectOption({ label: "Marie Dupont" });
  await page.getByLabel("Première ligne").fill("Heure de cours");
  await page.getByLabel("Prix unitaire HT").fill("1000");
  await page.getByRole("button", { name: "Créer le brouillon" }).click();
  await expect(page.getByRole("heading", { name: "Cours B2C" })).toBeVisible();
  await expect(page.getByText(/TTC 1[\s\u00a0\u202f]?200,00/)).toBeVisible();
  await expect(page.getByText("Montants en USD")).toBeVisible();
  await page.getByRole("button", { name: "Envoyer le devis" }).click();
  await expect(page.getByText(/DEV-\d{4}-0001 ·/)).toBeVisible();
  await expect(page.getByRole("heading", { name: "Destinataire" })).toBeVisible();
  await expect(page.getByText("Marie Dupont").first()).toBeVisible();
  await expect(page.getByText("Particulier", { exact: true })).toBeVisible();
  const quoteUrl = page.url();
  await page.getByRole("link", { name: "Clients", exact: true }).click();
  await page.getByRole("link", { name: "Marie Dupont" }).first().click();
  await expect(page).toHaveURL(/espace\/clients\//);
  await page.getByLabel("Nom", { exact: true }).fill("Martin");
  await page.getByRole("button", { name: "Enregistrer la fiche" }).click();
  await expect(page.getByRole("heading", { name: "Marie Martin" })).toBeVisible();
  await page.goto(quoteUrl);
  await expect(page.getByText("Marie Dupont").first()).toBeVisible();
  await expect(page.getByText("Marie Martin")).toHaveCount(0);
  await page.getByRole("button", { name: "Marquer accepté" }).click();
  await page.getByRole("button", { name: "Créer la facture" }).click();
  await expect(page).toHaveURL(/espace\/factures\//);
  await expect(page.getByText("Émise", { exact: true })).toBeVisible();
  await expect(page.getByText(/Échéance/)).toBeVisible();
  await expect(page.getByText("Marie Dupont").first()).toBeVisible();
  await expect(page.getByText(/TTC 1[\s\u00a0\u202f]?200,00/)).toBeVisible();
  await page.getByRole("link", { name: "Clients", exact: true }).click();
  await page.getByLabel("Identité").selectOption("COMPANY");
  await page.getByLabel("Raison sociale").fill("Atelier B2B");
  await page.getByRole("button", { name: "Créer la fiche" }).click();
  await expect(page.getByRole("heading", { name: "Atelier B2B" })).toBeVisible();
  await page.getByRole("link", { name: "Devis", exact: true }).click();
  await page.getByLabel("Titre").fill("Prestation B2B");
  await page.getByLabel("Destinataire").selectOption({ label: "Atelier B2B" });
  await page.getByLabel("Première ligne").fill("Mission");
  await page.getByLabel("Prix unitaire HT").fill("200");
  await page.getByRole("button", { name: "Créer le brouillon" }).click();
  await expect(page.getByRole("heading", { name: "Prestation B2B" })).toBeVisible();
  await page.getByRole("button", { name: "Envoyer le devis" }).click();
  await expect(page.getByText(/DEV-\d{4}-0002 ·/)).toBeVisible();
  await expect(page.getByText("Professionnel")).toBeVisible();
  await expect(page.getByText("Atelier B2B").first()).toBeVisible();
});
