import { test, expect } from "./test";
import { config } from "dotenv";
import { readdir, readFile, unlink } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { getDb } from "../../apps/web/src/lib/db";
config({ path: "apps/web/.env.local", quiet: true });
const emails: string[] = [];
const organization = `Clients ${randomUUID().slice(0, 8)}`;
const password = "Une phrase de passe navigateur 123!";
async function latestCode(email: string) {
  const dir = process.env.LOCAL_MAIL_DIR!;
  const files = await readdir(dir);
  const mails = await Promise.all(files.filter(file => file.endsWith(".json")).map(async file => JSON.parse(await readFile(path.join(dir, file), "utf8"))));
  const mail = mails.filter(item => item.to === email).sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0];
  return /\b\d{6}\b/.exec(mail.text)![0];
}
test.afterAll(async () => {
  const db = getDb();
  const memberships = await db.membership.findMany({ where: { user: { email: { in: emails } } } });
  const organizationIds = memberships.map(item => item.organizationId);
  await db.address.deleteMany({ where: { organizationId: { in: organizationIds } } });
  await db.customer.deleteMany({ where: { organizationId: { in: organizationIds } } });
  await db.user.deleteMany({ where: { email: { in: emails } } });
  await db.organization.deleteMany({ where: { id: { in: organizationIds } } });
  await db.authChallenge.deleteMany({ where: { email: { in: emails } } });
  const dir = process.env.LOCAL_MAIL_DIR!;
  for (const file of await readdir(dir).catch(() => [])) {
    if (file.endsWith(".json") && emails.includes(JSON.parse(await readFile(path.join(dir, file), "utf8")).to)) await unlink(path.join(dir, file));
  }
  await db.$disconnect();
});
test("création d’un client, adresse, archivage et accès particulier refusé", async ({ page, browser }) => {
  const ownerEmail = `browser-cust-${randomUUID()}@example.test`;
  const individualEmail = `browser-cust-ind-${randomUUID()}@example.test`;
  emails.push(ownerEmail, individualEmail);
  await page.goto("/inscription");
  await page.getByRole("radio", { name: /^Entreprise/ }).check();
  await page.getByLabel("Votre nom").fill("Camille Owner");
  await page.getByLabel("Nom de votre entreprise").fill(organization);
  await page.getByLabel("Adresse email").fill(ownerEmail);
  await page.getByLabel("Mot de passe", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Créer mon espace" }).click();
  await expect(page).toHaveURL(/verification/);
  await page.getByLabel("Code de vérification").fill(await latestCode(ownerEmail));
  await page.getByRole("button", { name: "Valider et accéder" }).click();
  await expect(page).toHaveURL(/espace/);
  await page.getByRole("link", { name: "Clients", exact: true }).click();
  await expect(page.getByRole("heading", { name: new RegExp(`Clients de ${organization}`) })).toBeVisible();
  await page.getByLabel("Raison sociale").fill("Atelier Dupont");
  await page.getByLabel("Adresse email").fill(`dupont-${randomUUID().slice(0, 8)}@client.test`);
  await page.getByLabel("Type").selectOption("CLIENT");
  await page.getByRole("button", { name: "Créer la fiche" }).click();
  await expect(page.getByRole("heading", { name: "Atelier Dupont" })).toBeVisible();
  await page.getByLabel("Libellé").fill("Siège");
  await page.getByLabel("Adresse", { exact: true }).fill("12 rue des Lilas");
  await page.getByLabel("Code postal").fill("75011");
  await page.getByLabel("Ville").fill("Paris");
  await page.getByLabel("Pays").selectOption("FR");
  await page.getByRole("button", { name: "Ajouter l’adresse" }).click();
  await expect(page.getByText("Paris")).toBeVisible();
  await page.getByRole("button", { name: "Archiver Atelier Dupont" }).click();
  await expect(page.getByText("Cette fiche est archivée")).toBeVisible();
  await page.goto("/espace/clients");
  await expect(page.getByRole("link", { name: "Atelier Dupont" })).toHaveCount(0);
  await page.getByRole("link", { name: "Archives" }).click();
  await expect(page.getByRole("link", { name: "Atelier Dupont" })).toBeVisible();
  await page.goto("/espace/clients");
  await page.getByLabel("Raison sociale").fill("Prospect Kanban");
  await page.getByLabel("Type").selectOption("PROSPECT");
  await page.getByRole("button", { name: "Créer la fiche" }).click();
  await page.getByRole("link", { name: "Pipeline", exact: true }).click();
  await expect(page.getByRole("heading", { name: new RegExp(`Pipeline de ${organization}`) })).toBeVisible();
  const card = page.locator("article", { hasText: "Prospect Kanban" });
  await card.getByLabel("Étape de Prospect Kanban").selectOption("CONTACTED");
  await card.getByRole("button", { name: "OK" }).click();
  await page.getByRole("link", { name: "Prospect Kanban" }).click();
  await expect(page.getByText("Nouveau → Contacté")).toBeVisible();
  await page.goto("/espace/clients");
  await page.getByLabel("Identité").selectOption("PERSON");
  await page.getByLabel("Prénom").fill("Marie");
  await page.getByLabel("Nom", { exact: true }).fill("Dupont");
  await page.getByLabel("Type").selectOption("CLIENT");
  await page.getByRole("button", { name: "Créer la fiche" }).click();
  await expect(page.getByRole("heading", { name: "Marie Dupont" })).toBeVisible();
  await expect(page.getByLabel("SIREN")).toHaveCount(0);
  await page.getByRole("link", { name: "Organisation" }).click();
  await expect(page.getByRole("heading", { name: new RegExp(`Identité de ${organization}`) })).toBeVisible();
  await page.getByLabel("Forme de l’émetteur").selectOption("COMPANY");
  await page.getByLabel("Raison sociale / nom légal").fill(`${organization} SAS`);
  await page.getByLabel("SIREN").fill("123456789");
  await page.getByRole("button", { name: "Enregistrer l’identité" }).click();
  await expect(page.getByText("L’identité de l’émetteur a été enregistrée.")).toBeVisible();
  const individual = await browser.newContext().then(context => context.newPage());
  await individual.goto("/inscription");
  await individual.getByRole("radio", { name: /^Particulier/ }).check();
  await individual.getByLabel("Votre nom").fill("Pat Particulier");
  await individual.getByLabel("Adresse email").fill(individualEmail);
  await individual.getByLabel("Mot de passe", { exact: true }).fill(password);
  await individual.getByRole("button", { name: "Créer mon espace" }).click();
  await expect(individual).toHaveURL(/verification/);
  await individual.getByLabel("Code de vérification").fill(await latestCode(individualEmail));
  await individual.getByRole("button", { name: "Valider et accéder" }).click();
  await expect(individual).toHaveURL(/espace/);
  await individual.goto("/espace/clients");
  await expect(individual).toHaveURL(/espace$/);
  await expect(individual.getByRole("link", { name: "Clients", exact: true })).toHaveCount(0);
  await expect(individual.getByRole("link", { name: "Pipeline", exact: true })).toHaveCount(0);
  await individual.close();
});
