import { test, expect } from "./test";
import { config } from "dotenv";
import { readdir, readFile, unlink } from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { getDb } from "../../apps/web/src/lib/db";
config({ path: "apps/web/.env.local", quiet: true });
const emails: string[] = [];
const organization = `Équipe ${randomUUID().slice(0, 8)}`;
const password = "Une phrase de passe navigateur 123!";
async function latestCode(email: string) {
  const dir = process.env.LOCAL_MAIL_DIR!;
  const files = await readdir(dir);
  const mails = await Promise.all(files.filter(file => file.endsWith(".json")).map(async file => JSON.parse(await readFile(path.join(dir, file), "utf8"))));
  const mail = mails.filter(item => item.to === email).sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0];
  return /\b\d{6}\b/.exec(mail.text)![0];
}
async function latestInviteLink(email: string) {
  const dir = process.env.LOCAL_MAIL_DIR!;
  const files = (await readdir(dir)).filter(file => file.startsWith("invite-"));
  const mails = await Promise.all(files.map(async file => JSON.parse(await readFile(path.join(dir, file), "utf8"))));
  const latest = mails.filter(item => item.to === email).sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0];
  return /https?:\/\/\S+/.exec(latest.text)![0];
}
test.afterAll(async () => {
  const db = getDb();
  const memberships = await db.membership.findMany({ where: { user: { email: { in: emails } } } });
  await db.user.deleteMany({ where: { email: { in: emails } } });
  await db.organization.deleteMany({ where: { id: { in: memberships.map(item => item.organizationId) } } });
  await db.authChallenge.deleteMany({ where: { email: { in: emails } } });
  const dir = process.env.LOCAL_MAIL_DIR!;
  for (const file of await readdir(dir).catch(() => [])) {
    if (file.endsWith(".json") && emails.includes(JSON.parse(await readFile(path.join(dir, file), "utf8")).to)) await unlink(path.join(dir, file));
  }
  await db.$disconnect();
});
test("invitation, création du collaborateur, rôle et accès particulier refusé", async ({ page, browser }) => {
  const ownerEmail = `browser-owner-${randomUUID()}@example.test`;
  const inviteEmail = `browser-invite-${randomUUID()}@example.test`;
  const individualEmail = `browser-ind-${randomUUID()}@example.test`;
  emails.push(ownerEmail, inviteEmail, individualEmail);
  await page.goto("/inscription");
  await page.getByRole("radio", { name: /^Entreprise/ }).check();
  await page.getByLabel("Votre nom").fill("Camille Owner");
  await page.getByLabel("Nom de votre entreprise").fill(organization);
  await page.getByLabel("Adresse email").fill(ownerEmail);
  await page.getByLabel("Mot de passe", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Créer mon espace" }).click();
  await expect(page).toHaveURL(/verification/);
  await page.getByLabel("Code de vérification").fill(await latestCode(ownerEmail));
  await page.getByRole("button", { name: "Valider et accéder" }).click();
  await expect(page).toHaveURL(/espace/);
  await page.getByRole("link", { name: "Équipe", exact: true }).click();
  await expect(page.getByRole("heading", { name: new RegExp(`Équipe de ${organization}`) })).toBeVisible();
  await page.getByLabel("Adresse email").fill(inviteEmail);
  await page.getByLabel("Rôle").selectOption("MEMBER");
  await page.getByRole("button", { name: "Envoyer l’invitation" }).click();
  await expect(page.getByRole("status")).toContainText("L’invitation a été envoyée");
  const invitee = await browser.newContext().then(context => context.newPage());
  await invitee.goto(await latestInviteLink(inviteEmail));
  await expect(invitee.getByText(organization)).toBeVisible();
  await invitee.getByLabel("Votre nom").fill("Alex Invité");
  await invitee.getByLabel("Mot de passe", { exact: true }).fill(password);
  await invitee.getByLabel("Confirmer le mot de passe", { exact: true }).fill(password);
  await invitee.getByRole("button", { name: "Créer mon compte et rejoindre" }).click();
  await expect(invitee).toHaveURL(/connexion\?invite=1/);
  await expect(invitee.getByRole("status")).toContainText("Votre accès a été créé");
  await invitee.getByLabel("Adresse email").fill(inviteEmail);
  await invitee.getByLabel("Mot de passe", { exact: true }).fill(password);
  await invitee.getByRole("button", { name: "Continuer", exact: true }).click();
  await expect(invitee).toHaveURL(/verification/);
  await invitee.getByLabel("Code de vérification").fill(await latestCode(inviteEmail));
  await invitee.getByRole("button", { name: "Valider et accéder" }).click();
  await expect(invitee).toHaveURL(/espace/);
  await expect(invitee.getByText("Membre")).toBeVisible();
  await page.reload();
  await expect(page.getByText(inviteEmail)).toBeVisible();
  await page.locator("article", { hasText: inviteEmail }).getByRole("button", { name: /Retirer/ }).click();
  await expect(page.getByText(inviteEmail)).toHaveCount(0);
  await invitee.close();
  const individual = await browser.newContext().then(context => context.newPage());
  await individual.goto("/inscription");
  await individual.getByRole("radio", { name: /^Particulier/ }).check();
  await individual.getByLabel("Votre nom").fill("Pat Particulier");
  await individual.getByLabel("Adresse email").fill(individualEmail);
  await individual.getByLabel("Mot de passe", { exact: true }).fill(password);
  await individual.getByRole("button", { name: "Créer mon espace" }).click();
  await expect(individual).toHaveURL(/verification/);
  await individual.getByLabel("Code de vérification").fill(await latestCode(individualEmail));
  await individual.getByRole("button", { name: "Valider et accéder" }).click();
  await expect(individual).toHaveURL(/espace/);
  await individual.goto("/espace/equipe");
  await expect(individual).toHaveURL(/espace$/);
  await expect(individual.getByRole("link", { name: "Équipe", exact: true })).toHaveCount(0);
  await individual.close();
});
